package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallRolePermission;
import org.linlinjava.litemall.db.domain.LitemallRolePermissionExample;

public interface LitemallRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     */
    long countByExample(LitemallRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Integer version, @Param("example") LitemallRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     */
    int insert(LitemallRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     */
    int insertSelective(LitemallRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRolePermission selectOneByExample(LitemallRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRolePermission selectOneByExampleSelective(@Param("example") LitemallRolePermissionExample example, @Param("selective") LitemallRolePermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallRolePermission> selectByExampleSelective(@Param("example") LitemallRolePermissionExample example, @Param("selective") LitemallRolePermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     */
    List<LitemallRolePermission> selectByExample(LitemallRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRolePermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallRolePermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     */
    LitemallRolePermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRolePermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Integer version, @Param("record") LitemallRolePermission record, @Param("example") LitemallRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Integer version, @Param("record") LitemallRolePermission record, @Param("example") LitemallRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallRolePermission record, @Param("example") LitemallRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallRolePermission record, @Param("example") LitemallRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKey(@Param("version") Integer version, @Param("record") LitemallRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeySelective(@Param("version") Integer version, @Param("record") LitemallRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}